-- MySQL Script generated by MySQL Workbench
-- Thu Jul 21 22:56:14 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BudgetApp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BudgetApp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BudgetApp` DEFAULT CHARACTER SET utf8 ;
USE `BudgetApp` ;

-- -----------------------------------------------------
-- Table `BudgetApp`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BudgetApp`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC));


-- -----------------------------------------------------
-- Table `BudgetApp`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BudgetApp`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `typeId` INT NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `BudgetApp`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BudgetApp`.`account` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `fk_account_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_account_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `BudgetApp`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BudgetApp`.`transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BudgetApp`.`transaction` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `money` DECIMAL(65,2) NOT NULL,
  `date` DATE NOT NULL,
  `type` INT NOT NULL,
  `account_id` INT NOT NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`id`, `account_id`, `category_id`),
  INDEX `fk_transaction_account1_idx` (`account_id` ASC),
  INDEX `fk_transaction_category1_idx` (`category_id` ASC),
  CONSTRAINT `fk_transaction_account1`
    FOREIGN KEY (`account_id`)
    REFERENCES `BudgetApp`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transaction_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `BudgetApp`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `BudgetApp`.`user`
-- -----------------------------------------------------
START TRANSACTION;
USE `BudgetApp`;
INSERT INTO `BudgetApp`.`user` (`id`, `firstName`, `lastName`, `email`, `password`) VALUES (DEFAULT, 'UserTest', 'UserTest', 'UserTest@admin.com', 'UserTest');

COMMIT;


-- -----------------------------------------------------
-- Data for table `BudgetApp`.`category`
-- -----------------------------------------------------
START TRANSACTION;
USE `BudgetApp`;
INSERT INTO `BudgetApp`.`category` (`id`, `name`, `typeId`) VALUES (DEFAULT, 'Investment', 1);
INSERT INTO `BudgetApp`.`category` (`id`, `name`, `typeId`) VALUES (DEFAULT, 'Salary', 1);
INSERT INTO `BudgetApp`.`category` (`id`, `name`, `typeId`) VALUES (DEFAULT, ' Interest', 1);
INSERT INTO `BudgetApp`.`category` (`id`, `name`, `typeId`) VALUES (DEFAULT, 'Gift', 1);
INSERT INTO `BudgetApp`.`category` (`id`, `name`, `typeId`) VALUES (DEFAULT, 'Others', 1);
INSERT INTO `BudgetApp`.`category` (`id`, `name`, `typeId`) VALUES (DEFAULT, 'Housing', 2);
INSERT INTO `BudgetApp`.`category` (`id`, `name`, `typeId`) VALUES (DEFAULT, 'Transportation', 2);
INSERT INTO `BudgetApp`.`category` (`id`, `name`, `typeId`) VALUES (DEFAULT, 'Food', 2);
INSERT INTO `BudgetApp`.`category` (`id`, `name`, `typeId`) VALUES (DEFAULT, 'Utilities', 2);
INSERT INTO `BudgetApp`.`category` (`id`, `name`, `typeId`) VALUES (DEFAULT, 'Health', 2);
INSERT INTO `BudgetApp`.`category` (`id`, `name`, `typeId`) VALUES (DEFAULT, 'Others', 2);

COMMIT;


-- -----------------------------------------------------
-- Data for table `BudgetApp`.`account`
-- -----------------------------------------------------
START TRANSACTION;
USE `BudgetApp`;
INSERT INTO `BudgetApp`.`account` (`id`, `user_id`) VALUES (DEFAULT, 1);

COMMIT;
